Реализация контроллеров
Alex-Ivash/java-shareit pull request #1
Opened 2024-12-11 07:24 UTC by Alex-Ivash

2024-12-11 09:07 UTC, tomattman requested changes
Привет, коментарии в основном на улучшение, есть парочка моментов которые надо поправить

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/BaseDtoMapper.java
> +package ru.practicum.shareit;
С одной стороны хорошо, что сделаны эти интерфейсы, с другой стороны они не все нужны, например для репозитория будет уже готовый интерфейс, для сервисов не всегда уместно
плюс можно было бы создать отдельный пакет под базовые классы

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/exception/ConflictException.java
> +public class ConflictException extends RuntimeException {
обычно более конкретные имена для классов с ошибками дают либо наоборот более абстрактные и детали в сообщении

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +package ru.practicum.shareit.item.controller;
чаще всего при таком разделении на пакеты не разбивают внутри по типам классов, разве что те, которых очень много, например dto

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/request/update/ItemRequestUpdateDtoMapper.java
> +public class ItemRequestUpdateDtoMapper implements BaseUpdateDtoMapper<ItemRequestUpdateDto, Item> {
чаще делают один класс маппер привязанный конкретно к сущности
и тут ты можешь сделать так же, ведь класс может имплементить сразу два интерейса

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/request/update/ItemRequestUpdateDtoMapper.java
> +public class ItemRequestUpdateDtoMapper implements BaseUpdateDtoMapper<ItemRequestUpdateDto, Item> {
хотя за счет того что одинаковые имена методов, не получится
это еще один момент против всех базовых интерфейсов, например тебе не надо приводить item к updateDto

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/response/ItemFromUserDto.java
> +public class ItemFromUserDto {
тут немного по имени
с таким именем нормально использовать будет только у юзера, а это в большинстве случаев не функционально, чаще всего просто разделить их на обычные дто, расширенные, и неполные версии, и тут можно было бы назваавть ItemShortDto  потому что это обрезанная версия основной dto

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/response/ItemResponseDtoMapper.java
> +public class ItemResponseDtoMapper implements BaseDtoMapper<ItemResponseDto, Item> {
снова мог бы быть оодин маппер с тремя методами
если хочешь, модешь посмотреть другие тулы для маппинга например одно из стандартных mapstruct

2024-12-11 09:07 UTC, tomattman commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    Long id;
модификаторы доступа

2024-12-11 09:44 UTC, Alex-Ivash commented on src/main/java/ru/practicum/shareit/item/dto/request/update/ItemRequestUpdateDtoMapper.java
> +public class ItemRequestUpdateDtoMapper implements BaseUpdateDtoMapper<ItemRequestUpdateDto, Item> {
Предлагаешь избавиться от базовых интерфейсов мапперов и просто сделать один маппер на сущность, который будет маппировать в разные DTO и обратно?
При этом, реализовывать только те маппинг методы туда и обратно, которые нужны? Типо item к updateDto действительно, вроде как, не нужен.

2024-12-11 09:49 UTC, Alex-Ivash commented on src/main/java/ru/practicum/shareit/BaseDtoMapper.java
> +package ru.practicum.shareit;
1. Да, я намучался, пытаясь выделить базовый сервис, из-за того, что DTO могут быть разные и разное кол-во в разных сервисах. Поэтому для сервисов это не всегда уместно?
2. Про готовый интерфейс для репозитория не понял :) Вроде полезно тут иметь базовый интерфейс, у нас же в репозиториях идет работа сущностями в основном. Или мы в будущем и туда DTO завезем, чтобы лишнего не выбирать из базы?
3. После чистки базовых классов останется не так много, нужен ли отдельный пакет, пока не понятно.

2024-12-11 09:52 UTC, Alex-Ivash commented on src/main/java/ru/practicum/shareit/item/dto/response/ItemResponseDtoMapper.java
> +public class ItemResponseDtoMapper implements BaseDtoMapper<ItemResponseDto, Item> {
mapstruct решил позже потрогать)
Стоит ли выделять логику обновления сущности из DTO в метод маппера_(например returnUpdatedFromDtoEntity в ItemRequestUpdateDtoMapper)_ или оставить эту логику в сервисе?

2024-12-12 09:26 UTC, tomattman commented on src/main/java/ru/practicum/shareit/BaseDtoMapper.java
> +package ru.practicum.shareit;
1) по сервисам, раньше у спринга было обязательно для всех сервисов добавлять интерфейсы, и это выглядело как напара интерфейс имплементация, для каждого сервиса, сейчас это не обязательно, и интерфейсы используют  в более подходяших способах, самый простой пример это как раз таки репозиторий, мы поределяем набор действией которые должен выполнять конкретный тип классов, и делаем инжект по интерфейсу, и если ты захочешь добавить новый источник данных, например получать данные из другого API то создаешь имплементацию, в ней реализуешь всю логику по работе с апи, но внешне ты работаешь с ней через интерфейс, следовательно во первых в ней будут все методы, которые мы привыкли использовать, а во вторых в коде никаких изменений, надо только правильно указать какую имплементацию использовать

2) это будет в слудующих работах, но если коротко, то у спринга есть готовый механизм работы с базами данныхю Создается интерфейс по заданным правилам, а спринг по нему сам сдлеает имплементацию, и никакого кода дополнительного писать не надо (если хочешь почитать сейчас, то почитай прос spring JPA) 

3) все по правилам проекта и на свой вкус, но дабавлять пакет только для одного класса как то странно, для двух, уже может быть но зависит от ситуациии

2024-12-12 09:28 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/request/update/ItemRequestUpdateDtoMapper.java
> +public class ItemRequestUpdateDtoMapper implements BaseUpdateDtoMapper<ItemRequestUpdateDto, Item> {
да, самый простой варинат
снова повторюсь, интерфейсы это конечно хорошо, но не всегда нужно
а в маппинг классе какие то методы можно перегрузить, и будет вообще хорошо

2024-12-12 09:30 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/response/ItemResponseDtoMapper.java
> +public class ItemResponseDtoMapper implements BaseDtoMapper<ItemResponseDto, Item> {
стоит делать так, чтобы функционал был логичен и логично разделен
например можно сделать метод mergeEntity который будет соездинять два обьекта, и в первом переписывать поля данными из второго, только если они там не null

2024-12-12 09:31 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/dto/response/ItemResponseDtoMapper.java
> +public class ItemResponseDtoMapper implements BaseDtoMapper<ItemResponseDto, Item> {
но это будет не маппинг, а отедельная логика

2024-12-12 09:32 UTC, tomattman approved these changes
Принято

2024-12-12 10:14 UTC, merged